sonar.projectKey=campconnect-backend
sonar.projectName=CampConnect Backend
sonar.projectVersion=0.0.1-SNAPSHOT

sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java/com/esprit/campconnect/Event,src/main/java/com/esprit/campconnect/Reservation
sonar.java.source=17
sonar.java.binaries=target/classes

sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=target/**,**/generated-sources/**
sonar.tests=src/test/java/com/esprit/campconnect/Event,src/test/java/com/esprit/campconnect/Reservation
sonar.test.inclusions=**/*Test.java
