server.port=8082
server.servlet.context-path=/api

spring.datasource.url=jdbc:mysql://mysql:3306/campconnect?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

cloudinary.cloud-name=dipa0djoj
cloudinary.api-key=311525424376963
cloudinary.api-secret=f35XkhGs1yjaf36wHCEfkuygzOA

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=30MB
app.upload.max-size=10485760
app.upload.dir=${APP_UPLOAD_DIR:/app/uploads/events}



app.stripe.secret-key=${STRIPE_SECRET_KEY:}
app.stripe.publishable-key=${STRIPE_PUBLISHABLE_KEY:}
app.stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET:}
app.stripe.currency=${PAYMENT_CURRENCY:usd}
app.stripe.frontend-base-url=${FRONTEND_BASE_URL:http://localhost:4200}
app.stripe.success-path=${PAYMENT_SUCCESS_PATH:/public/events/my-reservations}
app.stripe.cancel-path=${PAYMENT_CANCEL_PATH:/public/events/my-reservations}

app.google-maps.browser-api-key=${GOOGLE_MAPS_BROWSER_API_KEY:}
app.google-maps.server-api-key=${GOOGLE_MAPS_SERVER_API_KEY:}
app.google-maps.static-map-width=${GOOGLE_MAPS_STATIC_MAP_WIDTH:900}
app.google-maps.static-map-height=${GOOGLE_MAPS_STATIC_MAP_HEIGHT:420}
app.google-maps.static-map-zoom=${GOOGLE_MAPS_STATIC_MAP_ZOOM:14}

app.calendar.default-zone=${CALENDAR_DEFAULT_ZONE:Africa/Tunis}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USER}

spring.mail.password=${MAIL_PASS}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

notification.email.enabled=${NOTIFICATION_EMAIL_ENABLED:true}

brevo.api.base-url=${BREVO_API_BASE_URL:https://api.brevo.com/v3}
brevo.api.key=${BREVO_API_KEY:}
brevo.sender.email=${BREVO_SENDER_EMAIL:}
brevo.sender.name=${BREVO_SENDER_NAME:CampConnect}
brevo.sandbox-mode=${BREVO_SANDBOX_MODE:false}

app.jwt.secret=MyUltraSecureJwtSecretKeyThatIsAtLeast32CharsLong123
app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}
google.client.id=${GOOGLE_CLIENT_ID:dummy-google-client-id}
google.client.secret=${GOOGLE_CLIENT_SECRET:dummy-google-client-secret}

management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

twilio.account.sid=${TWILIO_ACCOUNT_SID:}
twilio.auth.token=${TWILIO_AUTH_TOKEN:}
twilio.phone.number=${TWILIO_PHONE_NUMBER:}